<?php


namespace app\modules\admin\controllers;


use yii\filters\AccessControl;
use yii\web\Controller;

class AppAdminController extends Controller
{

    public function beforeAction($action)
    {
        if (\Yii::$app->user->isGuest || \Yii::$app->user->id != 1) {
            $this->goHome();
        }

        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

}