<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "contacts".
 *
 * @property int $id
 * @property string $name
 * @property string $email
 * @property string $body
 */
class Contact extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'contacts';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['name', 'email', 'body'], 'required'],
            [['body'], 'string'],
            [['name', 'email'], 'string', 'max' => 255],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Имя',
            'email' => 'E-mail',
            'body' => 'Сообщение',
        ];
    }

    public function afterSave($insert, $changedAttributes)
    {
        $this->sendMail();
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }

    public function sendMail()
    {
        try {
            Yii::$app->mailer->compose('contact', ['model' => $this])
                ->setFrom([Yii::$app->params['senderEmail'] => Yii::$app->params['senderName']])
                ->setTo(Yii::$app->params['adminEmail'])
                ->setSubject('Сообщение из формы обратной связи сайта ' . Yii::$app->name )
                ->send();
        } catch (\Swift_TransportException $e) {
            Yii::error($e);
        }
    }

}
