<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "subscribes".
 *
 * @property int $id
 * @property string $name
 * @property string $email
 */
class Subscribe extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'subscribes';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['name', 'email'], 'required'],
            [['name', 'email'], 'string', 'max' => 255],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Name',
            'email' => 'Email',
        ];
    }

    public function afterSave($insert, $changedAttributes)
    {
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }


    public function sendMail()
    {
        try {
            Yii::$app->mailer->compose('subscribe', ['model' => $this])
                ->setFrom([Yii::$app->params['senderEmail'] => Yii::$app->params['senderName']])
                ->setTo($this->email)
                ->setSubject('Оформление подписки')
                ->send();
            Yii::$app->mailer->compose('admin', ['model' => $this])
                ->setFrom([Yii::$app->params['senderEmail'] => Yii::$app->params['senderName']])
                ->setTo(Yii::$app->params['adminEmail'])
                ->setSubject('Оформление подписки')
                ->send();

        } catch (\Swift_TransportException $e) {
            Yii::error($e);
        }
    }
}
