<?php

namespace app\models;

use yii\db\ActiveRecord;

/**
 * @property string $username
 * @property string $auth_key
 * @property int $id
 * @property string $password
 * @property int $isAdmin
 * @property string $email
 * @property string $img
 * @property bool $isActive
 * @property Comment[] $comments
 */
class User extends ActiveRecord implements \yii\web\IdentityInterface
{
    public $password_repeat;

    public static function tableName()
    {
        return 'users';
    }

    /**
     * {@inheritdoc}
     */
    public static function findIdentity($id)
    {
        return self::findOne($id);
    }

    /**
     * {@inheritdoc}
     */
    public static function findIdentityByAccessToken($token, $type = null)
    {

    }

    /**
     * Finds user by username
     *
     * @param string $username
     * @return static|null
     */
    public static function findByUsername($username)
    {
        return self::findOne(['username' => $username]);
    }

    /**
     * {@inheritdoc}
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * {@inheritdoc}
     */
    public function getAuthKey()
    {
        return $this->auth_key;
    }

    /**
     * {@inheritdoc}
     */
    public function validateAuthKey($authKey)
    {
        return $this->auth_key === $authKey;
    }

    /**
     * Validates password
     *
     * @param string $password password to validate
     * @return bool if password provided is valid for current user
     */
    public function validatePassword($password)
    {
        return \Yii::$app->getSecurity()->validatePassword($password, $this->password);
    }

    public function generateAuthKey()
    {
        $this->auth_key = \Yii::$app->security->generateRandomString();
    }

    public function afterSave($insert, $changedAttributes)
    {
        \Yii::$app->user->login($this);

        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }

    public function getComments()
    {
        return $this->hasMany(Comment::class, ['user_id' => 'id']);
    }

}
